# Generated by Django 4.2.1 on 2023-05-09 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidad',
            name='cantidad_discapacitados',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='cantidad_estudiantes',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
