# Generated by Django 4.2.1 on 2023-05-09 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_discapacidad', models.CharField(max_length=80)),
                ('cantidad_discapacitados', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=80)),
                ('cantidad_estudiantes', models.IntegerField(max_length=8)),
                ('nombre_universidad', models.CharField(max_length=80)),
                ('anio_informacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
    ]
